version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - durationcheck
    - gochecknoinits
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
          deny:
            - pkg: github.com/evanphx/json-patch
              desc: The 'github.com/evanphx/json-patch' package is superseded. Use pkg/utils/jsonpatch.go instead.
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: false
      no-global: ""
      context: ""
      static-msg: false
      no-raw-keys: false
      forbidden-keys:
        - level
        - msg
        - logger
        - source
        - stacktrace
        - time
      args-on-sep-lines: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'var-naming: don''t use an underscore in package name'
      - path: (.+)\.go$
        text: 'ST1003: should not use underscores in package names'
      - path: (.+)\.go$
        text: 'ST1005: error strings should not be capitalized'
      - path: (.+)\.go$
        text: 'error-strings: error strings should not be capitalized or end with punctuation or a newline'
      - path: (.+)\.go$
        text: 'ST1005: error strings should not end with punctuation or newlines'
      - path: (.+)\.go$
        text: 'dot-imports: should not use dot imports'
      - path: (.+)\.go$
        text: 'ST1001: should not use dot imports'
      - path: (.+)\.go$
        text: don't use `init` function
      - path: (.+)\.go$
        text: 'var-naming:'
      - path: (.+)\.go$
        text: 'ST1003: '
      - path: (.+)\.go$
        text: 'exported: type name will be used as .*'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/flant/)
    goimports:
      local-prefixes:
        - github.com/flant/
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
