# every push to a branch:
# - Run Go linters.
# - Check grammar with codespell.
name: Lint
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  go_linters:
    name: Run Go linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b . v1.54.2
          ./golangci-lint run --sort-results 

  codespell:
    name: Run codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Check out addon-operator code
        uses: actions/checkout@v3

      - name: Run codespell
        run: |
          pip install codespell==v1.17.1
          codespell --skip=".git,go.mod,go.sum,*.log,*.gif,*.png" -L witht,eventtypes,uint,uptodate
